[test]
levels = ["syntax", "install", "execution"]
publish = 'false'

[test.workflows]
timeout = 300
cpu = []
gpu = 'all'

[test.platforms]
# CPU platforms
linux = false
macos = false
windows = false
windows_portable = false
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
