[cuda]
packages = ['flash-attn','sageattention']

[node_reqs]
ComfyUI-GeometryPack = "PozzettiAndrea/ComfyUI-GeometryPack"
ComfyUI-Env-Manager = "PozzettiAndrea/ComfyUI-Env-Manager"
ComfyUI-Pulse-MeshAudit = "PozzettiAndrea/ComfyUI-Pulse-MeshAudit"