[test]
levels = ["syntax", "install", "execution"]
publish = 'true'

[test.workflows]
cpu = []
gpu = ["!mesh_audit"]

[test.platforms]
# CPU platforms
linux = false
macos = false
windows = false
windows_portable = false
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
